### ISSUE TITLE
IndexError: arrays used as indices must be of integer (or boolean) type

### ISSUE THREAD

**Issue by Minotaur-CN** [davidsandberg/mtcnn_face_alignment#2]
Dear david,
Thanks for your code! I ran your python mtcnn.py for a test Image, One error block the final result. Have you found that before? If so, could you give me some advise to cope that bug?
Thanks for you reply!
![screenshot from 2016-10-13 23-17-14](https://cloud.githubusercontent.com/assets/9798125/19355199/1e1cea60-919c-11e6-9194-28c94f6ea0ff.png)

**Comment by davidsandberg** [comment]
Hi,
The code has not been finished yet. Please check back in a week or so.
Sorry!!
